# Generated by Django 4.2.5 on 2023-11-11 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45, unique=True)),
                ('category_description', models.TextField(blank=True)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20, unique=True)),
                ('unit_price', models.IntegerField(default=0)),
                ('sale_price', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(default=0)),
                ('unit_measure', models.CharField(max_length=10, unique=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website1.equipmentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=10, unique=True)),
                ('stock_taken', models.IntegerField(default=0)),
                ('transaction_amount', models.IntegerField(default=0)),
                ('transaction_date', models.DateField(auto_now=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website1.product')),
            ],
        ),
    ]
